// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"net/http"
)

// Injectors from wire.go:

func InitializeEvent(phrase string) (Event, error) {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event, err := NewEvent(greeter)
	if err != nil {
		return Event{}, err
	}
	return event, nil
}

func InitializeUserStore(ctx context.Context, info *ConnectionInfo, debug bool) (*UserStore, error) {
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	userStore := NewUserStore(config, client)
	return userStore, nil
}

func InitializeBookStore(ctx context.Context, info *ConnectionInfo, debug bool) (*BookStore, error) {
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	bookStore := NewBookStore(config, client)
	return bookStore, nil
}

func InitializeServer(ctx context.Context, info *ConnectionInfo, debug bool) (*http.ServeMux, error) {
	indexService := NewIndexService()
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	userStore := NewUserStore(config, client)
	userService := NewUserService(userStore)
	bookStore := NewBookStore(config, client)
	bookService := NewBookService(userStore, bookStore)
	serveMux := NewServer(indexService, userService, bookService)
	return serveMux, nil
}
