// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package internal

import (
	"context"
	"github.com/gorilla/mux"
)

// Injectors from wire.go:

func InitializeUserStore(ctx context.Context, info *ConnectionInfo, debug bool) (*UserStore, error) {
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	userStore := NewUserStore(config, client)
	return userStore, nil
}

func InitializeBookStore(ctx context.Context, info *ConnectionInfo, debug bool) (*BookStore, error) {
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	bookStore := NewBookStore(config, client)
	return bookStore, nil
}

func InitializeServer(ctx context.Context, info *ConnectionInfo, debug bool) (*mux.Router, error) {
	indexService := NewIndexService()
	config := NewDefaultConfig(debug)
	client, err := NewClient(ctx, info)
	if err != nil {
		return nil, err
	}
	userStore := NewUserStore(config, client)
	userService := NewUserService(userStore)
	bookStore := NewBookStore(config, client)
	bookService := NewBookService(userStore, bookStore)
	router := NewServer(indexService, userService, bookService)
	return router, nil
}
